/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giu;

import Logica.Expresiones;
import Logica.Imp_Caj;
import Logica.Imp_Clie;
import Logica.Imp_Cuen;
import Logica.Imp_transf;
import Logica.ManCajero;
import Logica.ManCliente;
import Logica.ManCuenta;
import Logica.ManTransferencia;
import clases.Cajero;
import clases.Cliente;
import clases.Cuenta;
import clases.Transferencia;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author lenovo
 */
public class Retiro extends javax.swing.JFrame {

    Imp_Clie objImpCli = new Imp_Clie();
    Imp_Cuen objImpCue = new Imp_Cuen();
    Imp_Caj objImpCaj = new Imp_Caj();
    Imp_transf objImpTra = new Imp_transf();
    ManCajero objManCaj = new ManCajero();
    ManCliente objManCli = new ManCliente();
    ManCuenta objManCue = new ManCuenta();
    ManTransferencia objManTra = new ManTransferencia();
    ArrayList<Cliente> ArrayClientes = new ArrayList<Cliente>();
    ArrayList<Cuenta> ArrayCuentas = new ArrayList<Cuenta>();
    ArrayList<Cajero> ArrayCajeros = new ArrayList<Cajero>();
    ArrayList<Transferencia> ArrayTransacciones = new ArrayList<Transferencia>();
    Cuenta objCue = new Cuenta();
    Cliente objCli = new Cliente();
    Cajero objCaj = new Cajero();
    Transferencia objTra = new Transferencia();

    public Retiro() {
        initComponents();
        ArrayClientes = objImpCli.ImportarClientes();
        ArrayCuentas = objImpCue.ImportarCuentas();
        ArrayCajeros = objImpCaj.ImportarCajeros();
        ArrayTransacciones = objImpTra.ImportarTransaccion();
        setTitle("Retiro");
        objCaj = objManCaj.BuscarCajero(ArrayCajeros, "987");
        this.jcajID.setText(objCaj.getId_Cajero());
        this.jcajNom.setText(objCaj.getNombre());
        this.jcajApe.setText(objCaj.getApellido());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextcuenta = new javax.swing.JTextField();
        jTextfecha = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jTextMonto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jsaldo = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jnombre = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jnumTra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jcajNom = new javax.swing.JTextField();
        jcajApe = new javax.swing.JTextField();
        jcajID = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Retiro");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 120, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Cedula");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 70, 140, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Cuenta");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));
        getContentPane().add(jTextcuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, -1));

        jTextfecha.setEnabled(false);
        jTextfecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextfechaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 130, -1));

        jButton1.setText("Validar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 150, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Monto");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        jTextMonto.setEnabled(false);
        getContentPane().add(jTextMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 160, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 200, 200));

        jButton2.setText("Realizar");
        jButton2.setEnabled(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, -1, -1));

        jButton3.setText("PRESENTAR");
        jButton3.setEnabled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Fecha");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jLabel4.setText("Saldo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, -1, -1));

        jsaldo.setEnabled(false);
        getContentPane().add(jsaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 150, -1));

        jLabel9.setText("Nombre");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jnombre.setEnabled(false);
        getContentPane().add(jnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 150, -1));

        jLabel10.setText("Transaccion #:");

        jnumTra.setEnabled(false);
        jnumTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jnumTraActionPerformed(evt);
            }
        });

        jLabel11.setText("Atendido por:");

        jcajNom.setEnabled(false);
        jcajNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcajNomActionPerformed(evt);
            }
        });

        jcajApe.setEnabled(false);
        jcajApe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcajApeActionPerformed(evt);
            }
        });

        jcajID.setEnabled(false);
        jcajID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcajIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(jcajNom, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcajApe, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jcajID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jnumTra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jnumTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jcajNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcajApe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jcajID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 390, 90));

        jButton4.setText("Salir");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 80, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jTextfechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextfechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextfechaActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        objCue = objManCue.BuscarCuenta(ArrayCuentas, this.jTextcuenta.getText());
        objCli = objManCli.BuscarCliente(ArrayClientes, this.jTextCedula.getText());
        try {
            if (objCue.getNumero().equals(this.jTextcuenta.getText()) && objCue.getCliente().getCedula().equals(this.jTextCedula.getText())) {
                this.jsaldo.setText(String.valueOf(objCue.getSaldo()));
                this.jnombre.setText(objCli.getNombre());
                this.jTextMonto.setEnabled(true);
                this.jTextfecha.setEnabled(true);
                this.jButton3.setEnabled(true);

            } else {
               JOptionPane.showMessageDialog(rootPane, "No es el titular de la cuenta");
                this.jTextcuenta.setText("");
                this.jTextCedula.setText("");
            }
        } catch (Exception e) {
          JOptionPane.showMessageDialog(rootPane, "No es el titular de la cuenta");
                this.jTextcuenta.setText("");
                this.jTextCedula.setText("");
        }

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        try {
            boolean aux = false;
            Cuenta objAux = new Cuenta();
            objAux = objCue;
            objCue = objManCue.RetiroCuenta(objCue, Double.parseDouble(this.jTextMonto.getText()));
            if (objCue.getSaldo() != objAux.getSaldo()) {
                JOptionPane.showMessageDialog(rootPane, "Saldo Menor al Minimo\n"
                        + "Ingrese valor a retirar nuevamenete");
                aux = true;
            }
            if (aux = true) {
                objTra = objManTra.CrearTransaccion(objCli, objCaj, objCue, ArrayTransacciones);
            }
            this.jcajID.setText(String.valueOf(objTra.getId_transaccion()));
            ArrayTransacciones.add(objTra);
            ArrayCuentas.set(ArrayCuentas.indexOf(objCue), objCue);
            try {
                objManTra.GuardaTransaccion(ArrayTransacciones);
                objManCue.GuardarCuenta(ArrayCuentas);
            } catch (IOException ex) {
                Logger.getLogger(Retiro.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NumberFormatException e) {

        } finally {
            //TextFields en vacio de nuevo
            this.jTextcuenta.setText("");
            this.jTextCedula.setText("");
            this.jnombre.setText("");
            this.jsaldo.setText("");
            this.jTextMonto.setText("");
            this.jTextfecha.setText("");
            //Desactivar Botones
            this.jButton2.setEnabled(false);
            this.jButton3.setEnabled(false);

            //Desactivar TextFields
            this.jnombre.setEnabled(false);
            this.jsaldo.setEnabled(false);
            this.jTextMonto.setEnabled(false);
            this.jTextfecha.setEnabled(false);

        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Expresiones objexp = new Expresiones();
        String S = "Cedula: " + this.jTextCedula.getText() + "\n Beneficiario:" + this.jnombre.getText() + "\n Cuenta:" + this.jTextcuenta.getText() + "\n Saldo:" + this.jsaldo.getText()
                + "\n Monto:" + this.jTextMonto.getText()
                + "\n Fecha:" + this.jTextfecha.getText()
                + "\n";
        String fecha = this.jTextfecha.getText();
        this.jTextArea1.setText(S);
        if (objexp.fecha(fecha)) {
            JOptionPane.showMessageDialog(null, "fecha  correcta");
            this.jButton2.setEnabled(true);
            this.jTextArea1.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Fecha no correcta");
            this.jButton2.setEnabled(false);
            this.jTextArea1.setEnabled(false);

        }

        if (objexp.soloNumeros(this.jTextMonto.getText())) {
            JOptionPane.showMessageDialog(null, "ingrese solo digitos");
            this.jButton2.setEnabled(false);
            this.jTextArea1.setEnabled(false);

        }

        double saldito = Double.parseDouble(this.jsaldo.getText());
        switch (objCue.getOpcion()) {
            case 1:
                saldito = saldito - 20;
                if (saldito <= Double.parseDouble(this.jTextMonto.getText())) {
                    JOptionPane.showMessageDialog(null, "No tienes saldo suficiente");
                    this.jButton2.setEnabled(false);
                    this.jTextArea1.setEnabled(false);
                }
                break;
            case 2:
                saldito = saldito - 50;
                if (saldito <= Double.parseDouble(this.jTextMonto.getText())) {
                    JOptionPane.showMessageDialog(null, "No tiene saldo suficiente");
                    this.jButton2.setEnabled(false);
                    this.jTextArea1.setEnabled(false);

                }
                break;
        }


    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jcajNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcajNomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcajNomActionPerformed

    private void jcajApeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcajApeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcajApeActionPerformed

    private void jcajIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcajIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcajIDActionPerformed

    private void jnumTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jnumTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jnumTraActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        Login objReg = new Login();
        objReg.setVisible(true);
        Retiro obretiro = new Retiro();
        obretiro.setVisible(false);
        dispose();
    }//GEN-LAST:event_jButton4MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retiro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retiro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextMonto;
    private javax.swing.JTextField jTextcuenta;
    private javax.swing.JTextField jTextfecha;
    private javax.swing.JTextField jcajApe;
    private javax.swing.JTextField jcajID;
    private javax.swing.JTextField jcajNom;
    private javax.swing.JTextField jnombre;
    private javax.swing.JTextField jnumTra;
    private javax.swing.JTextField jsaldo;
    // End of variables declaration//GEN-END:variables
}
